### PR TITLE
Optimized assets. Added issues link. Made gradlew executable. Smaller icon.

### PR DESCRIPTION
**Pull request by RDKRACZ**
- Lossless compression with [Leanify](https://github.com/JayXon/Leanify)
- Resized icon to 256x256, the original was added to the /images directory as a backup
- Added executable permission to the gradlew file
- Added issues tag to the fabric.mod.json file

### CODE REVIEW

**Review by tvanprooyen — CHANGES_REQUESTED** [review]
Not sure if it was intended, but all the textures are being "edited". I'd remove them from the change list. Otherwise, it looks good and I'll approve it with those changes. Thanks!

**Comment by tvanprooyen** [comment]
Let me know if you intended for the texture changes

**Comment by RDKRACZ** [comment]
Not sure what you mean by edited. All textures were losslessly compressed. There are no visual differences, only in the way these images are "written" (more space-efficient).
I can explain how can you do this by yourself if you want.
Sadly Github does not preview image files in the "Files changed" tab (Gitlab does).
You can check this Github bot - https://imgbot.net/ - it does the same thing I have done manually but it's not that good since it uses older programs to achieve its results. Here it is in action https://github.com/RDKRACZ/mbm/pull/3.

After optimization, the jar size went down from 2,1 MB to 1,5 MB.

I have done PRs like this for other MC mods in the past and they were accepted. I can link them here if you want.

**Comment by tvanprooyen** [comment]
No worries, i was just wondering. Ill send it though

**Pull request merged**
